### ISSUE TITLE
Return devices as they reply

### ISSUE THREAD

**Issue by jeremyVignelles** [vmartos/OnvifSharp#12]
Hi,
We're considering using your library in our project.

We have a UI where we want to show the discovered devices, and users would expect devices to appear quite immediately, while the scan can last 30seconds.

Unfortunately, this is not possible with the current API because of this line: 

https://github.com/vmartos/onvif-discovery/blob/c231b1df95039761d3f6ea09ff8ef3fe32864412/OnvifDiscovery/Discovery.cs#L50

A new API entry point could be created with this signature:

```cs
public async Task Discover(Action<DiscoveryDevice> onDeviceDiscovered, int timeout, CancellationToken cancellationToken = default)
```

Thanks to the `onDeviceDiscovered` callback, items could be made available as they reply.
To avoid code duplication, the current entry point could be a wrapper around this new method, like so:

```cs
public async Task<IEnumerable<DiscoveryDevice>> Discover (int timeout, CancellationToken cancellationToken = default)
{
	var devices = new List<DiscoveryDevice> ();
	await this.Discover(devices.Add, timeout, cancellationToken);
	return devices;
}
```

What do you think?
We can make the PR if you want.

**Comment by vicmaeg** [comment]
Hey,

Sorry for taking so long to answer, I don't know what happened but I did not receive any notification.

Regarding the issue, this library was intended as an implementation that follows ONVIF discovery devices from the official docs. This just only sends one probe message, so even if you wait for 30 seconds probably all the cameras will respond to that probe message in no more than 1 or 2 seconds.

Is true that maybe some cameras can take more than 3 seconds to respond, or even some messages can be lost. So I can improve the code to make a long running version that sends multiple probe messages and accepts an Action as an argument, or even to have an ObservableCollection as property to just observe changes on that collection. I will think about it.

Also I Accept Pull Request, so if you have already did some work feel free to create one PR.

**Comment by jeremyVignelles** [comment]
Hey,
OK, probably not 30seconds, but you get the point, I want to show my camera as soon as they replay to avoid waiting.
Sending several  probes could be an idea, but that can also be done externally, right?

I'm not a fan of exposing an ObservableCollection, because nothing prevents you to call multiple `Discover` in parallel at the moment, and introducing a property would break that.

We didn't start the implementation here, but I'll try to give it a try in a few days.

**Comment by vicmaeg** [comment]
Ok, thanks for your thoughts, in fact is a good idea. When I have time I will probably work on it. But let me know if you decide to start the implementation and I'll happy to merge it.

**Comment by jeremyVignelles** [comment]
Starting implementation, stay tuned...
