### ISSUE TITLE
Duplicate and wrong Model, Manufacturer name

### ISSUE THREAD

**Issue by pubpy2015** [vmartos/OnvifSharp#17]
Hi,

If Manufacturer name contain space character as "Flir System", your lib only detect "Flir".
![ảnh](https://user-images.githubusercontent.com/59004953/141769420-a9dd9d07-79f6-4454-b0ed-2d7c36a4f1fc.png)

onvif://www.onvif.org/type/Network_Video_Transmitter onvif://www.onvif.org/type/ptz onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/video_analytics onvif://www.onvif.org/name/ONVIF_ICAMERA onvif://www.onvif.org/hardware/MSTAR_IPNC onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/location/China onvif://www.onvif.org/location/Shenzhen 
onvif://www.onvif.org/type/Network_Video_Transmitter onvif://www.onvif.org/type/ptz onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/video_analytics onvif://www.onvif.org/name/ONVIF_ICAMERA onvif://www.onvif.org/hardware/MSTAR_IPNC onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/location/China onvif://www.onvif.org/location/Shenzhen 
onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/hardware/CM-6204-11-I onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/Profile/G onvif://www.onvif.org/name/FLIR%20CM-6204-11-I%20K816600858 onvif://www.onvif.org/manufacturer/FLIR%20Systems onvif://www.onvif.org/manufacturer/DVTel dvtel://www.dvtel.com/quasar/gen2/quadhd flir://www.flir.com/security/quasar/gen2/quadhd onvif://www.onvif.org/location/country/America onvif://www.onvif.org/location/country/America onvif://www.onvif.org/acc/uuid/0b6b62ea-b49a-49dc-906a-001bd880cd6c onvif://www.onvif.org/acc/mac/00-1b-d8-80-cd-6c onvif://www.onvif.org/acc/firmware/version/fs20160805NSZ onvif://www.onvif.org/acc/mfr/FLIR%20Systems 
onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/hardware/CM-6204-11-I onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/Profile/G onvif://www.onvif.org/name/FLIR%20CM-6204-11-I%20K816600858 onvif://www.onvif.org/manufacturer/FLIR%20Systems onvif://www.onvif.org/manufacturer/DVTel dvtel://www.dvtel.com/quasar/gen2/quadhd flir://www.flir.com/security/quasar/gen2/quadhd onvif://www.onvif.org/location/country/America onvif://www.onvif.org/location/country/America onvif://www.onvif.org/acc/uuid/0b6b62ea-b49a-49dc-906a-001bd880cd6c onvif://www.onvif.org/acc/mac/00-1b-d8-80-cd-6c onvif://www.onvif.org/acc/firmware/version/fs20160805NSZ onvif://www.onvif.org/acc/mfr/FLIR%20Systems 
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/type/Network_Video_Transmitter onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/hardware/GV-UNP2500 onvif://www.onvif.org/location/country/taiwan onvif://www.onvif.org/name/Geovision onvif://www.onvif.org/acc/firmware/version/v3.12%202017-06-
onvif://www.onvif.org/name/Panasonic onvif://www.onvif.org/hardware/WV-V1330LK onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/type/Network_Video_Transmitter onvif://www.onvif.org/extension/unique_identifier onvif://www.onvif.org/location/office
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/type/Network_Video_Transmitter onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/hardware/GV-UNP2500 onvif://www.onvif.org/location/country/taiwan onvif://www.onvif.org/name/Geovision onvif://www.onvif.org/acc/firmware/version/v3.12%202017-06-
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/type/ptz onvif://www.onvif.org/type/video_analytics onvif://www.onvif.org/hardware/2.0-H3M-DO1 onvif://www.onvif.org/avigilon/mac/00-18-85-14-3e-0a onvif://www.onvif.org/avigilon/firmware/version/2.6.0.150(15529) onvif://www.onvif.org/avigilon/scopes/changeId/sessionId/12688_3147 onvif://www.onvif.org/name/acc/Xu%e1%ba%a5t%20c%e1%ba%a3nh%204 onvif://www.onvif.org/location/acc/Xuat%20canh%204
onvif://www.onvif.org/name/Panasonic onvif://www.onvif.org/hardware/WV-V1330LK onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/type/Network_Video_Transmitter onvif://www.onvif.org/extension/unique_identifier onvif://www.onvif.org/location/office
 onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/type/ptz onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/TC-C32TS%20SPEC%3AI8%2FA%2FE%2FY%2FM%2FH%2F2.7-13.5mm onvif://www.onvif.org/mfr/ipcamera onvif://www.onvif.org/location/country/china onvif://www.onvif.org/location/city/tianjin onvif://www.onvif.org/mac onvif://www.onvif.org/firmware/APP_V3.3.0.20200606 onvif://www.onvif.org/name/TC-C32TS%20SPEC%3AI8%2FA%2FE%2FY%2FM%2FH%2F2.7-13.5mm onvif://www.onvif.org/type/ipcamera onvif://www.onvif.org/Profile/G
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/type/ptz onvif://www.onvif.org/type/video_analytics onvif://www.onvif.org/hardware/2.0-H3M-DO1 onvif://www.onvif.org/avigilon/mac/00-18-85-14-3e-0a onvif://www.onvif.org/avigilon/firmware/version/2.6.0.150(15529) onvif://www.onvif.org/avigilon/scopes/changeId/sessionId/12688_3147 onvif://www.onvif.org/name/acc/Xu%e1%ba%a5t%20c%e1%ba%a3nh%204 onvif://www.onvif.org/location/acc/Xuat%20canh%204
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/FI710-L onvif://www.onvif.org/location/country/China onvif://www.onvif.org/name/STD
 onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/type/ptz onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/TC-C32TS%20SPEC%3AI8%2FA%2FE%2FY%2FM%2FH%2F2.7-13.5mm onvif://www.onvif.org/mfr/ipcamera onvif://www.onvif.org/location/country/china onvif://www.onvif.org/location/city/tianjin onvif://www.onvif.org/mac onvif://www.onvif.org/firmware/APP_V3.3.0.20200606 onvif://www.onvif.org/name/TC-C32TS%20SPEC%3AI8%2FA%2FE%2FY%2FM%2FH%2F2.7-13.5mm onvif://www.onvif.org/type/ipcamera onvif://www.onvif.org/Profile/G
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/Profile/G onvif://www.onvif.org/type/basic onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/name/ArielFHDIPCamera onvif://www.onvif.org/hardware/CM-3102-11-I dvtel://www.dvtel.com/ariel/gen2 dvtel://www.dvtel.com/ariel/gen2/minidome onvif://www.onvif.org/location/ onvif://www.onvif.org/acc/uuid/98190dc2-0890-4ef8-ac9a-001bd8601f8d onvif://www.onvif.org/acc/mac/00-1b-d8-60-1f-8d onvif://www.onvif.org/acc/firmware/version/01.05.32.5 onvif://www.onvif.org/acc/mfr/FLIR%20Systems
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/FI710-L onvif://www.onvif.org/location/country/China onvif://www.onvif.org/name/STD
onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/Profile/G onvif://www.onvif.org/type/basic onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/name/ArielFHDIPCamera onvif://www.onvif.org/hardware/CM-3102-11-I dvtel://www.dvtel.com/ariel/gen2 dvtel://www.dvtel.com/ariel/gen2/minidome onvif://www.onvif.org/location/ onvif://www.onvif.org/acc/uuid/98190dc2-0890-4ef8-ac9a-001bd8601f8d onvif://www.onvif.org/acc/mac/00-1b-d8-60-1f-8d onvif://www.onvif.org/acc/firmware/version/01.05.32.5 onvif://www.onvif.org/acc/mfr/FLIR%20Systems

**Comment by pubpy2015** [comment]
this is on ONVIF Device Manager:
![ảnh](https://user-images.githubusercontent.com/59004953/141769733-74633677-cc0a-4c4a-9d9c-9ba1c195b1dd.png)

**Comment by vicmaeg** [comment]
Hi! Thanks for open this issue and all the detailed information about the scopes.

I have been very busy and I couldn't work on that. I have the fix regarding the parsing of the Model and Manufacturer, it will be merged with https://github.com/vmartos/onvif-discovery/pull/18 when all tests passes.

The idea is to create a new version after the merge

Regarding the duplication it might possible because the probe responses are being received from multiple network interfaces. I still need to investigate how to fix it.

**Comment by vicmaeg** [comment]
The model and manufacturer has been merged, I reopen the issue to continue investigating the duplication

**Comment by vicmaeg** [comment]
@pubpy2015 published package 1.2.0 with the fix, also included the scopes in the DiscoveryDevice if you want to parse more information from there. Please write here if you see any issue, thanks!

**Comment by Jiayuan-Hu** [comment]
hi, i found i can use this package to find onvif camera ip in subnet. but if i would like to find onvif ip address in different subnets, cant use. 
for example: i can find from 192.168.10.1-192.168.10.25 these ip address, but i can find 192.168.9.5 this ip address

**Comment by vicmaeg** [comment]
Fixed with https://github.com/vmartos/onvif-discovery/pull/20
