### ISSUE TITLE
Not Discovering the Device often

### ISSUE THREAD

**Issue by irajaman** [vmartos/OnvifSharp#2]
This solution is not discovering the device and throws OperationCanceledException often. @vmartos  Please let me know if you face this issue before or if you know the solution? 

Below is the block of code which is throwing exception instead of giving result.

public static async Task<T> WithCancellation<T> (this Task<T> task, CancellationToken cancellationToken)
		{
			var tcs = new TaskCompletionSource<bool> ();
			using (cancellationToken.Register (s => ((TaskCompletionSource<bool>)s).TrySetResult (true), tcs)) {
				if (task != await Task.WhenAny (task, tcs.Task)) {
					throw new OperationCanceledException (cancellationToken);
				}
			}
			return await task;
		}

**Comment by vicmaeg** [comment]
Hello @irajaman,

Could you tell me on which environment did you run the program (OS, .Net core framework or Full framework)?  Did you use the OnvifSharp.CLI .net core program? 
I will consider taking it a look. 

Thank you.
