### ISSUE TITLE
Detect ONVIF MessageVersion

### ISSUE THREAD

**Issue by ispysoftware** [vmartos/OnvifSharp#23]
Hello thanks for the code!
Any way to add in the message version into the discovery results, like
Soap12WSAddressing10, Soap11WSAddressingAugust2004, Soap12WSAddressing10, Soap12WSAddressingAugust2004 or Soap11?

**Comment by vicmaeg** [comment]
Hi @ispysoftware ,

I am only in mantaining mode for bugfixes only, I don´t have plans to add new features.  But I am open to approve PRs.

In any case I am trying to understand the request, as far as I am concerned the naming Soap12WSAddressing10, Soap11WSAddressingAugust2004, Soap12WSAddressing10, Soap12WSAddressingAugust2004 or Soap11 are related to the MessageVersion from WCF libraries, this naming are not a standard, although my guess is that when receiving the soap response (XML) I could parse the `xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"` and translate that into version?

As I said I don´t have too much time now, and I have plans first to migrate to .NET6. But if I have time in the future I will try to do something, also I might consider adding a field like `RawMessage` with the full raw response message as string, and make this configurable, this way someone can use the RawMessage to manually do some kind of parsing to extract other useful information that I am missing.

**Comment by ispysoftware** [comment]
hello sorry i'd forgotten about this - and i think it just came up as i was debugging something else and ended up not being relevant - I should have closed it. Thanks for the response anyway.
