### ISSUE TITLE
UdpClientFactory filters to ethernet devices only

### ISSUE THREAD

**Issue by woody3k** [vmartos/OnvifSharp#24]
Hi,

I was wondering if there is a reason UdpClientFactory IsValidAdaptor filters to ethernet devices only?
This might limit usefulness on Xamarin platforms, not sure what NetworkInterfaceType is used on mobile devices.

It would be useful to us if discovery could probe wireless interfaces as well, thinking as an optional filter? (ie. ethernet only by default, but can configure with a list of NetworkInterfaceTypes to filter to)

Happy to create a P/R along these lines, does it sound like a reasonable feature to add?

**Comment by vicmaeg** [comment]
Hi @woody3k,

Sorry for the late reply, but looking into the code:

```
if (adapter.NetworkInterfaceType != NetworkInterfaceType.Ethernet &&
    !adapter.NetworkInterfaceType.ToString ().ToLower ().StartsWith ("wireless")) return false;
```

this statement will return false (Not Valid) for adapter other than Ethernet and that doesn't start with wireless, notice the &&, so any wireless adapters will not return false here.

When I do local testing, I only have a valid wireless adapter and that wireless adapter is being used.

If you had any issues with some wireless adapter on some mobile device, maybe it doesn't start with "wireless" I accept PRs, for the moment I will close this with this comment, but feel free to reopen it or create a PR if some wireless network adapter is not discovered.

Thanks.

**Comment by woody3k** [comment]
Hi @vicmaeg,
Thanks for the response and great explanation.
The double-negative clearly fooled me, not sure I actually saw the wireless interface being ignored, and may have been wondering why a camera wasn't detected on both eth & wifi (laptop with both) but there was probably a different explanation for that.
