### ISSUE TITLE
Quick Start Guide?

### ISSUE THREAD

**Issue by jwdinius** [vmartos/OnvifSharp#29]
Hello!  I came across your package while trying to find tools to find my doorbell camera's rtsp streaming address.

I don't use Windows and am not well-versed in DotNet or C#.  It would be helpful for me (and others like me) if an executable was included with this package or, failing that, a completely worked-out example of how to discover onvif devices on your network and write their properties to the console or file.  The README is of some help, but it is incomplete.  Your first example references local variables `discovery` and `cancellationToken` that are not declared anywhere.

**Comment by vicmaeg** [comment]
Hi @jwdinius 

There is a working sample program in the folder OnvifDiscovery.CLI from this repository.

You can clone this repo and if you have the dotnet sdk installed in your system you can run the following command in the OnvifDiscovery.CLI folder:

dotnet run

This command builds the OnvifDiscovery.CLI.csproj and runs it. The program logs to console the address of the discovered cameras.

I am thinking that it might be useful to pack it as a dotnet tool and push it. When I have time I might do that.

**Comment by jwdinius** [comment]
> Hi @jwdinius
> 
> There is a working sample program in the folder OnvifDiscovery.CLI from this repository.
> 
> You can clone this repo and if you have the dotnet sdk installed in your system you can run the following command in the OnvifDiscovery.CLI folder:
> 
> dotnet run
> 
> This command builds the OnvifDiscovery.CLI.csproj and runs it. The program logs to console the address of the discovered cameras.
> 
> I am thinking that it might be useful to pack it as a dotnet tool and push it. When I have time I might do that.

This worked like a charm.  I cloned the repo, opened the `OnvifDiscovery.CLI` folder in VS Code, and executed `dotnet run`.
